name: Update 'say' lists

env:
  PNPM_VERSION: 8
  NODE_VERSION: 20

on:
  workflow_dispatch:
  push:
    paths:
      - 'say/**/*.txt'
      - '!say/compiler/**'

jobs:
  built:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Run script
        run: |
          cd say/compiler
          pnpm install
          pnpm run compile

      - name: Check for changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "update 'say' filter lists"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
